[package]
name = "rustybun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanoserde = "0.1.30"
rustyline = "10.0.0"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
